apiVersion: v1
kind: Service
metadata:
  name: {{ include "kcp-operator.fullname" . }}
  labels:
    {{- include "kcp-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8443
      targetPort: http
      protocol: TCP
      name: metrics
    - port: 9443
      targetPort: http
      protocol: TCP
      name: webhook
  selector:
    {{- include "kcp-operator.selectorLabels" . | nindent 4 }}
