externalHostname: "kcp.dev.local"
etcd:
  enabled: false
kcp:
  # tag is set via --set flag to make it more dynamic for testing purposes
  volumeClassName: "standard"
  tokenAuth:
    enabled: true
  etcd:
    serverAddress: embedded
kcpFrontProxy:
  # tag is set via --set flag to make it more dynamic for testing purposes
  openshiftRoute:
    enabled: false
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
