externalHostname: ""
etcd:
  enabled: true
  image: quay.io/coreos/etcd
  tag: v3.5.4
  resources:
    requests:
      cpu: 500m
      memory: 2Gi
    limits:
      # cpu: 1
     memory: 20Gi
  volumeSize: 8Gi
  profiling:
    enabled: false
kcp:
  image: ghcr.io/kcp-dev/kcp
  tag: latest
  v: "3"
  logicalClusterAdminFlag: true
  externalLogicalClusterAdminFlag: true
  resources:
    requests:
      memory: 5Gi
      cpu: 100m
    limits:
      # cpu: 1
      memory: 20Gi
  volumeClassName: gp2-csi
  etcd:
    serverAddress: https://etcd:2379
    clientCertificate:
      issuer: etcd-client-issuer
      commonName: root
  volumeSize: 1Gi
  extraFlags: []
  profiling:
    enabled: false
    port: 6060
  tokenAuth:
    enabled: false
    fileName: auth-token.csv
    config: |
        user-1-token,user-1,1111-1111-1111-1111,"team-1"
        admin-token,admin,5555-5555-5555-5555,"system:masters"
kcpFrontProxy:
  image: ghcr.io/kcp-dev/kcp
  tag: latest
  v: "4"
  shardsKubeConfigFlag: true
  openshiftRoute:
    enabled: false
  ingress:
    enabled: false
    annotations: {}
    secret: ""
  gateway:
    enabled: false
    className: ""
  certificate:
    issuerSpec: {selfSigned: {}}
  profiling:
    enabled: false
    port: 6060
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      # cpu: 1
      memory: 1Gi
oidc: {}
audit:
  enabled: false
  volumeSize: 1Gi
  volumeClassName: "gp2-csi"
  policy:
    dir: /etc/kcp/audit
    fileName: audit-policy.yml
    config: |
      # Log all requests at the Metadata level.
      apiVersion: audit.k8s.io/v1
      kind: Policy
      rules:
      - level: Metadata
  log:
    maxAge: "10"
    maxSize: "250"
    maxBackup: "1"
    dir: /var/audit
certificates:
  privateKeys:
    algorithm: RSA
    size: 2048
  subject: {}
githubUserEditAccess:
- test
