{{- if .Values.etcd.enabled -}}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: etcd-client-issuer
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: "etcd"
spec:
  ca:
    secretName: etcd-client-bootstrap-secret
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: etcd-peer-issuer
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: "etcd"
spec:
  ca:
    secretName: etcd-peer-bootstrap-secret
{{- end }}
