{{- if .Values.etcd.enabled -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "etcd.fullname" . }}-client-ca
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: "etcd"
spec:
  isCA: true
  commonName: {{ include "etcd.fullname" . }}-client-bootstrap
  secretName: {{ include "etcd.fullname" . }}-client-bootstrap-secret
  privateKey:
    {{- toYaml .Values.certificates.privateKeys | nindent 4 }}
  issuerRef:
    name: {{ include "kcp.fullname" . }}-pki
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "etcd.fullname" . }}-peer-ca
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: "etcd"
spec:
  isCA: true
  commonName: {{ include "etcd.fullname" . }}-peer-bootstrap
  secretName: {{ include "etcd.fullname" . }}-peer-bootstrap-secret
  privateKey:
    {{- toYaml .Values.certificates.privateKeys | nindent 4 }}
  issuerRef:
    name: {{ include "kcp.fullname" . }}-pki
    kind: Issuer
    group: cert-manager.io
{{- end }}
