apiVersion: v1
kind: Secret
metadata:
  name: proxy-kcp-kubeconfig
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
stringData:
  kubeconfig: |
    apiVersion: v1
    clusters:
    - cluster:
        # this references the CA certificate that signed kcp's serving certificate
        # (kcp-server-issuer by default)
        certificate-authority: /etc/kcp/tls/server/ca.crt
        server: https://kcp:6443
      name: system:admin
    contexts:
    - context:
        cluster: system:admin
        user: admin
      name: system:admin
    current-context: system:admin
    kind: Config
    preferences: {}
    users:
    - name: admin
      user:
        client-certificate: /etc/kcp-front-proxy/client-cert-for-kubeconfig/tls.crt
        client-key: /etc/kcp-front-proxy/client-cert-for-kubeconfig/tls.key
