apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kcp-front-proxy
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: "front-proxy"
spec:
  secretName: kcp-front-proxy-cert
  duration: 8760h0m0s # 365d
  renewBefore: 360h0m0s # 15d
  {{ with .Values.certificates.subject }}
  subject:
    {{- toYaml . | nindent 4 }}
  {{ end}}
  privateKey:
    {{- toYaml .Values.certificates.privateKeys | nindent 4 }}
  usages:
    - server auth
  dnsNames:
    - "{{ .Values.externalHostname }}"
  issuerRef:
{{ .Values.kcpFrontProxy.certificateIssuer | toYaml | indent 4 }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kcp-front-proxy-kcp-client-cert
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: "front-proxy"
spec:
  secretName: kcp-front-proxy-kcp-client-cert
  duration: 8760h0m0s # 365d
  renewBefore: 360h0m0s # 15d
  {{ with .Values.certificates.subject }}
  subject:
    {{- toYaml . | nindent 4 }}
  {{ end}}
  privateKey:
    {{- toYaml .Values.certificates.privateKeys | nindent 4 }}
  usages:
    - client auth
  dnsNames:
    - "kcp-front-proxy"
  issuerRef:
    name: kcp-requestheader-client-issuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: client-cert-for-kubeconfig
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: "front-proxy"
spec:
  secretName: client-cert-for-kubeconfig
  duration: 8760h0m0s # 365d
  renewBefore: 360h0m0s # 15d
  commonName: kcp-front-proxy
  subject:
    organizations:
      - "system:masters"
  privateKey:
    {{- toYaml .Values.certificates.privateKeys | nindent 4 }}
  usages:
    - client auth
  issuerRef:
    name: kcp-server-client-issuer
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kcp-service-account-cert
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: "front-proxy"
spec:
  commonName: kcp-service-account-cert
  secretName: kcp-service-account-cert
  issuerRef:
    name: kcp-service-account-issuer
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kcp-front-proxy-virtual-workspaces-client-cert
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: "front-proxy"
spec:
  secretName: kcp-front-proxy-virtual-workspaces-client-cert
  duration: 8760h0m0s # 365d
  renewBefore: 360h0m0s # 15d
  {{ with .Values.certificates.subject }}
  subject:
    {{- toYaml . | nindent 4 }}
  {{ end}}
  privateKey:
    {{- toYaml .Values.certificates.privateKeys | nindent 4 }}
  usages:
    - client auth
  dnsNames:
    - "kcp-front-proxy"
  issuerRef:
    name: kcp-requestheader-client-issuer
---
