apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "frontproxy.fullname" . }}-config
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: "front-proxy"
data:
  path-mapping.yaml: |
{{ .Values.kcpFrontProxy.pathMapping | toYaml | indent 4 }}
