apiVersion: v1
kind: Secret
metadata:
  name: logical-cluster-admin-kubeconfig
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
stringData:
  kubeconfig: |
    apiVersion: v1
    clusters:
    - cluster:
        # this references the CA certificate that signed kcp's serving certificate
        # (kcp-server-issuer by default)
        certificate-authority: /etc/kcp/tls/server/ca.crt
        server: https://kcp:6443
      name: logical-cluster:admin
    contexts:
    - context:
        cluster: logical-cluster:admin
        user: logical-cluster-admin
      name: logical-cluster
    current-context: logical-cluster
    kind: Config
    preferences: {}
    users:
    - name: logical-cluster-admin
      user:
        client-certificate: /etc/kcp/logical-cluster-admin/client-cert-for-kubeconfig/tls.crt
        client-key: /etc/kcp/logical-cluster-admin/client-cert-for-kubeconfig/tls.key
