apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kcp
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: "server"
spec:
  secretName: kcp-cert
  duration: 8760h0m0s # 365d
  renewBefore: 360h0m0s # 15d
  {{- with .Values.certificates.subject }}
  subject:
    {{- toYaml . | nindent 4 }}
  {{- end}}
  privateKey:
    {{- toYaml .Values.certificates.privateKeys | nindent 4 }}
  usages:
    - server auth
  dnsNames:
  {{- range .Values.certificates.dnsNames }}
  - {{ . }}
  {{- end }}
  issuerRef:
    name: kcp-server-issuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kcp-virtual-workspaces
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: "server"
spec:
  secretName: kcp-virtual-workspaces-cert
  duration: 8760h0m0s # 365d
  renewBefore: 360h0m0s # 15d
  {{- with .Values.certificates.subject }}
  subject:
    {{- toYaml . | nindent 4 }}
  {{- end}}
  privateKey:
    {{- toYaml .Values.certificates.privateKeys | nindent 4 }}
  usages:
    - server auth
  dnsNames:
  {{- range .Values.certificates.dnsNames }}
  - {{ . }}
  {{- end }}
  issuerRef:
    name: kcp-server-issuer
{{- if .Values.etcd.enabled }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kcp-etcd-client
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: "server"
spec:
  secretName: kcp-etcd-client
  duration: 8760h0m0s # 365d
  renewBefore: 360h0m0s # 15d
  commonName: {{ .Values.kcp.etcd.clientCertificate.commonName }}
  privateKey:
    {{- toYaml .Values.certificates.privateKeys | nindent 4 }}
  usages:
    - client auth
  issuerRef:
    name: {{ .Values.kcp.etcd.clientCertificate.issuer }}
{{- end }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: logical-cluster-admin-client-cert-for-kubeconfig
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: "server"
spec:
  secretName: logical-cluster-admin-client-cert-for-kubeconfig
  duration: 8760h0m0s # 365d
  renewBefore: 360h0m0s # 15d
  commonName: logical-cluster-admin
  subject:
    organizations:
      - "system:kcp:logical-cluster-admin"
  privateKey:
    {{- toYaml .Values.certificates.privateKeys | nindent 4 }}
  usages:
    - client auth
  issuerRef:
    name: kcp-server-client-issuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: external-logical-cluster-admin-client-cert-for-kubeconfig
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: "server"
spec:
  secretName: external-logical-cluster-admin-client-cert-for-kubeconfig
  duration: 8760h0m0s # 365d
  renewBefore: 360h0m0s # 15d
  commonName: external-logical-cluster-admin
  subject:
    organizations:
      - "system:kcp:external-logical-cluster-admin"
  privateKey:
    {{- toYaml .Values.certificates.privateKeys | nindent 4 }}
  usages:
    - client auth
  issuerRef:
    name: kcp-client-issuer
