{{- if .Values.kcp.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "kcp.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: "server"
spec:
  minAvailable: {{ .Values.kcp.podDisruptionBudget.minAvailable | default 1 }}
  selector:
    matchLabels:
      {{- include "common.labels" . | nindent 6 }}
      app.kubernetes.io/component: "server"
{{- end }}
